# Generated by Django 3.0.4 on 2020-04-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Disease'),
        ),
    ]
